config/routes.rb
Rails.application.routes.draw do
  get 'welcome/login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#login'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article = Article.find(params[:id])
      end
    def new
    end
    def create
        @article = Article.new(params[:article])
 
        @article.save
        redirect_to @articl
    end 
    private
  def article_params
    params.require(:article).permit(:title, :text)
  end            
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit%>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/home/tung/myblog/app/assets/stylesheets/welcome.scss" rel="stylesheet">
    <title>Login</title>
</head>
<body>
    <p> <input type="text" placeholder="Nhập tên đăng nhập" name="username"> </p>
    <p> <input type="password" placeholder="Nhập mật khẩu" name="password"></p>
    <button  type="submit">Đăng nhập</button>
    <button type="Reset">Reset</button>
</body>
</html>